config/routes.rb
Rails.application.routes.draw do
  root "livros#index"

  resources :livros do
    member do
      put :borrow
      put :return
    end
    collection do
      get :list
    end
  end

  devise_for :usuarios do
    collection do
      get :livros
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :usuarios, only: [] do
    collection do
      get :livros
    end
  end

  namespace :api do
    namespace :v1 do
      resources :usuario_livros, only: [:index, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/search_field.rb
module SearchField
  extend ActiveSupport::Concern

  included do
    scope :search_all_fields, ->(text, columns) {
      columns = columns.compact_blank
      safe_columns = columns.map do |column|
        table_name, column_name = column.split('.')
        "#{connection.quote_table_name(table_name)}.#{connection.quote_column_name(column_name)}"
      end
      sanitized_sql = sanitize_sql_for_conditions(["CONCAT_WS(' ', #{safe_columns.join(', ')}) ILIKE ?", "%#{text}%"])
      where(sanitized_sql)
    }
  end
end

app/models/livro.rb
class Livro < ApplicationRecord
  include SearchField

  has_many :usuario_livros, dependent: :destroy
  has_many :usuarios, through: :usuario_livros

  has_one_attached :image

  def image_as_thumbnail
    image.variant(resize_to_limit: [407, 201]).processed
  end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum :tipo, [:admin, :user], default: :user

  has_many :usuario_livros
  has_many :livros, through: :usuario_livros

end

app/models/usuario_livro.rb
class UsuarioLivro < ApplicationRecord
  belongs_to :usuario
  belongs_to :livro
end

app/controllers/api/api_controller.rb
# app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::API
    before_action :verify_token

    private

    def verify_token
      provided_token = request.headers['Authorization']
      if provided_token.blank? || provided_token != Rails.application.credentials.api_token
        render json: { error: 'Unauthorized' }, status: :unauthorized
      end
    end
  end
end

app/controllers/api/v1/usuario_livros_controller.rb
# app/controllers/api/v1/usuario_livros_controller.rb
module Api
  module V1
    class UsuarioLivrosController < Api::ApiController
      def index
        usuario_livros = UsuarioLivro.all
        render json: usuario_livros
      end

      def show
        usuario_livro = UsuarioLivro.find(params[:id])
        render json: usuario_livro
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_usuario!

  layout :select_layout

  include Pagy::Backend

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :tipo])
  end

  def select_layout
    if devise_controller?
      action_name == "edit" || action_name == "update" ? "application" : "devise"
    else
      "application"
    end
  end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy borrow return ]

  # GET /livros or /livros.json
  def index
    @pagy, @livros = pagy(
      Livro.where.not(
        id: UsuarioLivro.select("first_value(livro_id) over (partition by livro_id order by created_at desc)")
                        .where(returned_at: nil)
      ).distinct.order(created_at: :desc)
    )
  end

  # GET /livros/1 or /livros/1.json
  def show
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    if @livro.save
      redirect_to livros_path, notice: "Livro foi criado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy!

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro foi excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  def borrow
    @livro.usuario_livros.create!(usuario: current_usuario, borrowed_at: Time.current)

    redirect_to livros_usuarios_path, notice: "Livro foi emprestado com sucesso."
  end

  def return
    @livro.usuario_livros.find_by!(returned_at: nil).update!(returned_at: Time.current)

    redirect_to livros_usuarios_path, notice: "Livro foi devolvido com sucesso."
  end

  def list
    livros = Livro.left_joins(:usuario_livros)
         .where(usuario_livros: { id: nil })
         .or(Livro.left_joins(:usuario_livros).where.not(usuario_livros: { returned_at: nil }))
         .distinct
         .order(created_at: :desc)

    columns = %w[livros.nome livros.descricao]
    livros = livros.search_all_fields(params[:search], columns) if params[:search].present?

    @pagy, @livros = pagy(livros)

    render(partial: 'livros', locals: { livros: @livros })
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:nome, :descricao, :image)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  include Pagy::Backend

  def livros
    @pagy, @livros = pagy(current_usuario.usuario_livros.includes(:livro).order(created_at: :desc))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiBibliotecaEscolar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="page">
      <header class="navbar navbar-expand-sm navbar-light d-print-none">
        <div class="container-xl">
          <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
          </h1>
          <div class="navbar-nav flex-row order-md-last">
            <div class="nav-item dropdown">
              <a class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
                <%= image_tag "no_photo.jpeg", class: "avatar avatar-sm" %>
                <div class="d-none d-xl-block ps-2">
                  <div><%= current_usuario.name %></div>
                  <div class="mt-1 small text-muted"><%= current_usuario.email%></div>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <%= link_to "Meus livros", livros_usuarios_path, class: "dropdown-item" %>
                <%= link_to "Configurações", edit_usuario_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= button_to "Logout", destroy_usuario_session_path(@driver), class: "dropdown-item", method: :delete, data: { turbo: false } %>
              </div>
            </div>
          </div>
        </div>
      </header>
      <header class="navbar-expand-md navbar-light">
        <div class="collapse navbar-collapse" id="navbar-menu">
          <div class="navbar navbar-light">
            <div class="container-xl">
              <div class="row flex-fill align-items-center">
                <div class="col">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="/livros">
                          <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M5 12l-2 0l9 -9l9 9l-2 0"></path><path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path><path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path></svg>
                          </span>
                        <span class="nav-link-title">
                            Home
                          </span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Livros', livros_path, class: "nav-link" %>
                    </li>
                  </ul>
                </div>
                <div class="col-2 d-none d-xxl-block">
                  <div class="my-2 my-md-0 flex-grow-1 flex-md-grow-0 order-first order-md-last">

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div class="page-wrapper">
        <div class="page-body">
          <div class="container">
            <%= yield %>
          </div>
        </div>
        <footer class="footer footer-transparent d-print-none">
          <div class="container-xl">
            <div class="row text-center align-items-center flex-row-reverse">
            </div>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiBibliotecaEscolar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class=" d-flex flex-column">
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<div class="page-body">
  <%= form_with(model: livro, html: { class: "card card-md" }, format: :html) do |form| %>
      <div class="card-body">
        <% if livro.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading"><%= pluralize(livro.errors.count, "erro") %> impediu que este livro fosse salvo:</h4>
            <ul>
              <% livro.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mb-3">
        <%= form.label :image, 'Imagem' %>
        <%= form.file_field :image %>
        </div>

        <div class="mb-3">
          <%= form.label :nome, 'Nome do Livro:', class: 'form-label' %>
          <%= form.text_field :nome, class: 'form-control', placeholder: "Digite o nome do livro" %>
        </div>

        <div class="mb-3">
          <%= form.label :descricao, 'Descrição:', class: 'form-label' %>
          <%= form.text_area :descricao, class: 'form-control', placeholder: "Digite a descrição do livro", rows: 3 %>
        </div>

        <div class="form-footer">
          <%= form.submit "Criar", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
</div>

app/views/livros/_livro.html.erb
<div class="card-body">
  <div class="datagrid">
    <div class="datagrid-item">
      <div class="datagrid-title">Nome</div>
      <div class="datagrid-content"><%= livro.nome %></div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">Descrição</div>
      <div class="datagrid-content"><%= livro.descricao %></div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">Disponibilidade</div>
      <div class="datagrid-content">
        <span class="badge bg-success">Disponível</span>
      </div>
    </div>
  </div>
  <% if current_usuario.user? %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= button_to "Emprestar Livro", borrow_livro_path(livro), method: :put, class: "btn btn-primary", data: { turbo: false } %>
    </div>
  <% end %>
</div>

app/views/livros/_livros.html.erb
<%= turbo_frame_tag "livros" do %>
  <div class="row row-cards">
    <% livros.each do |livro| %>
      <div class="col-sm-6 col-lg-4 mb-3">
        <%= link_to livro_path(livro), data: { turbo_stream: true }, method: :get do %>
          <div class="card card-sm">
            <% if livro.image.attached? %>
              <%= image_tag livro.image, class: "card-img-top", style: "max-height: 271px; object-fit: cover;" %>
            <% else %>
              <img src="https://preview.tabler.io/static/photos/beautiful-blonde-woman-relaxing-with-a-can-of-coke-on-a-tree-stump-by-the-beach.jpg" class="card-img-top" alt="Default Image">
            <% end %>
            <div class="card-body">
              <div class="d-flex align-items-center">
                <div>
                  <div><%= livro.nome %></div>
                  <div class="text-secondary"><%= livro.descricao %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="card-footer d-flex align-items-center">
    <p class="m-0 text-muted">Mostrando <span><%= @livros.size %></span> de <span><%= @pagy.count %></span> registros</p>
    <ul class="pagination m-0 ms-auto">
      <%== pagy_bootstrap_nav(@pagy) %>
    </ul>
  </div>
<% end %>

app/views/livros/_modal.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="modal modal-blur fade" id="modal-report" tabindex="-1" aria-hidden="true" data-controller="modal">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= livro.nome %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render 'livro', livro: livro %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h1>Editing livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Show this livro", @livro %> |
  <%= link_to "Back to livros", livros_path %>
</div>

app/views/livros/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/notices', resource: current_usuario %>
  </div>
  <div class="page-wrapper">
    <header class="page-header d-print-none" tabindex="0">
      <div class="container-xl">
        <div class="row g-2 align-items-center">
          <div class="col">
            <h2 class="page-title">
              Livros
            </h2>
          </div>

          <div class="col-auto ms-auto d-print-none">
            <div class="btn-list">
              <%= form_with url: list_livros_path, method: :get, data: { turbo_frame: 'livros', controller: 'search-form', action: 'input->search-form#submit' } do |form| %>
                <div class="input-icon">
                  <%= form.text_field :search, placeholder: "Search", value: params[:search], class: "form-control border border-blue-500 rounded p-2" %>
                  <span class="input-icon-addon">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path><path d="M21 21l-6 -6"></path></svg>
                  </span>
                </div>
              <% end %>
              <% if current_usuario.admin? %>
                <%= link_to new_livro_path, class: "btn btn-primary d-none d-sm-inline-block" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                  Criar novo livro
                <%end%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Page body -->
    <main class="page-body" tabindex="0">
      <div class="container-xl">
        <%= render 'livros', livros: @livros %>
      </div>
    </main>
  </div>
</div>

<%= turbo_frame_tag 'modal' %>

app/views/livros/new.html.erb
<div class="row align-items-center">
  <div class="col">
    <!-- Page pre-title -->
    <div class="page-pretitle">
      Form
    </div>
    <h2 class="page-title">
      Novo livro
    </h2>
  </div>
  <!-- Page title actions -->
  <div class="col-auto ms-auto d-print-none">
    <div class="btn-list">
      <%= link_to "Voltar para livros", livros_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<%= render "form", livro: @livro %>

app/views/livros/show.html.erb
<div class="page-wrapper">
  <div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <h2 class="page-title">
            Livros
          </h2>
        </div>
        <!-- Page title actions -->
        <div class="col-auto ms-auto d-print-none">
          <div class="d-flex">
            <%= link_to "Back to livros", livros_path, class: "btn btn-sm btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Livro info</h3>
        </div>
        <div class="card-body">
          <div class="datagrid">
            <div class="datagrid-item">
              <div class="datagrid-title">Livro</div>
              <div class="datagrid-content">
                <div class="d-flex align-items-center">
                  <%= link_to @livro['avatar'], target: :_blank do %>
                    <%= image_tag(@livro['avatar'], class: "avatar avatar-xs me-2 rounded") %>
                  <% end %>
                  <%= @livro['first_name'] %> <%= @livro['last_name'] %>
                </div>
              </div>
            </div>
            <div class="datagrid-item">
              <div class="datagrid-title">Name</div>
              <div class="datagrid-content"><%= @livro['first_name'] %> <%= @livro['last_name'] %></div>
            </div>
            <div class="datagrid-item">
              <div class="datagrid-title">Email</div>
              <div class="datagrid-content"><%= @livro['email'] %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/livros/show.turbo_stream.erb
<%= turbo_stream.replace 'modal', partial: 'modal', locals: { livro: @livro } %>

app/views/shared/_notices.html.erb
<% flash.each do |type, message| %>
  <% if message.is_a?(String) %>
    <div class="alert alert-dismissible" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Erros de Validação do Modelo -->
<% if resource&.errors&.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Erros encontrados:</strong>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/usuarios/livros.html.erb
<div class="container mt-3">
  <div class="row">
    <%= render 'shared/notices', resource: current_usuario %>
  </div>
  <div class="card">

    <div class="card-header">
      <h3 class="card-title">Meus Livros</h3>
    </div>
    <div class="table-responsive">
      <table class="table card-table table-vcenter text-nowrap datatable">
        <thead>
        <tr>
          <th>Nome</th>
          <th>Descrição</th>
          <th>Emprestado em</th>
          <th>Devolvido em</th>
        </tr>
        </thead>
        <tbody>
        <% if @livros.empty? %>
          <tr>
            <td colspan="4" class="text-center">Nenhum livro disponível</td>
          </tr>
        <% else %>
          <% @livros.each do |usuario_livro| %>
            <tr>
              <td><%= usuario_livro.livro.nome %></td>
              <td><%= usuario_livro.livro.descricao %></td>
              <td><%= usuario_livro.borrowed_at ? l(usuario_livro.borrowed_at, format: :long) : "Não informado" %></td>
              <td>
                <%= usuario_livro.returned_at ? l(usuario_livro.returned_at, format: :long) : "Não devolvido" %>
                <% unless usuario_livro.returned_at %>
                  <%= button_to 'Devolver Livro', return_livro_path(usuario_livro.livro), method: :put, class: 'btn btn-warning btn-sm', data: { turbo: false } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="card-footer d-flex align-items-center">
      <p class="m-0 text-muted">Mostrando <span><%= @livros.size %></span> de <span><%= @pagy.count %></span> registros</p>
      <ul class="pagination m-0 ms-auto">
        <%== pagy_bootstrap_nav(@pagy) %>
      </ul>
    </div>
  </div>
</div>